libero/reviewer-submission

package.json
yarn.lock

- Add husky
- Address peer dependency warning for ts-jest (warning " > ts-jest@24.0.2" has incorrect peer dependency "jest@>=24 <25".)
- Introduce husky
- Amend package name
- Amend version to bring inline with other dev projects
- Add author

Address peer dependency warning

---

Makefile
xpub-schema.sql

The schema is loaded into a postgres schema called `xpublegacy`

Add make command for loading in schema

---

.travis.yml
Makefile
docker-compose.xpub-postgres.yml
xpub-postgres.Dockerfile

Closes #42 
Creates a custom postgres image with the xpub schema already loaded for use for integration tests

build xpub postgres docker image

---

.gitignore
package.json
tasks/merge-schemas.ts
yarn.lock

Add graphql linter

---

.travis.yml
Dockerfile
package.json
tsconfig.json

switch to node 12

---

config/config.example.json
package.json
src/config.ts
src/main.ts
tests/app.test.ts
tests/config/reviewer-submission.json
yarn.lock

Apply resolver depth and complexity limiter

---

src/schemas/submission.graphql
src/submission/resolvers/submission.ts

Add mutation resolver

---

src/submission/repositories/types.ts
src/submission/repositories/xpub-submission-root.ts
src/submission/repositories/xpub-team.test.ts
src/submission/repositories/xpub-team.ts
src/submission/types.ts

Created a team repository in the same style and design as submission.
Closes #83

83 Team repo

---

src/submission/repositories/types.ts
src/submission/types.ts
src/teams/repositories/types.ts
src/teams/repositories/xpub-team.test.ts
src/teams/repositories/xpub-team.ts
src/teams/types.ts

Create the Teams Service

---

src/main.ts

Destroy the connections on shutdown as per ticket

---

tests/app.test.ts

Restore test for upload

---

src/application/wizard/resolvers.ts
src/application/wizard/service.test.ts
src/application/wizard/service.ts
src/schemas/wizard.graphql

Part of https://github.com/libero/reviewer/issues/620

Rename saveDetailsPage to saveAuthorPage

---

src/application/wizard/resolvers.ts
src/application/wizard/service.test.ts
src/application/wizard/service.ts
src/domain/file/repositories/xpub-file.ts
src/domain/file/services/file-service.test.ts
src/domain/file/services/file-service.ts
src/domain/file/services/models/file.ts
src/domain/submission/services/models/submission.ts
src/schemas/wizard.graphql
tests/app.test.ts

Add upload supporting file mutation

---

src/application/dashboard/service.ts
src/application/permission/service.test.ts
src/application/permission/service.ts
src/application/wizard/service.ts

Add more tests to illustrate how the Permission Service is to be used.

Add more permission tests

---

src/application/wizard/service.test.ts
src/application/wizard/service.ts
src/domain/file/services/file-service.test.ts
src/domain/file/services/file-service.ts
src/domain/file/services/models/file.ts
src/schemas/submission.graphql

Closes libero/reviewer#592
* Changed the file service to return signed download links
* Wizard service fetches full submission each time (using new getFullSubmission method)

Add download link from s3

---

src/application/permission/service.test.ts
src/application/wizard/resolvers.ts
src/application/wizard/service.ts
src/domain/submission/repositories/xpub-submission-root.test.ts
src/domain/submission/repositories/xpub-submission-root.ts
src/domain/submission/services/exporter/file-generators/article.test.data.ts
src/domain/submission/services/exporter/file-generators/disclosure.ts
src/domain/submission/services/models/submission-schema.ts
src/domain/submission/services/models/submission.test.ts
src/domain/submission/services/models/submission.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/domain/submission/types.ts
src/domain/teams/repositories/types.ts
src/schemas/submission.graphql
tests/dashboard.test.ts
tests/test.utils.ts
tests/wizard.files.test.ts
tests/wizard.submit.test.ts

Closes https://github.com/libero/reviewer/issues/650

Reshape the submission object

---

src/domain/submission/services/models/submission.test.ts
src/domain/submission/services/models/submission.ts
src/domain/submission/services/submission-service.test.ts
tests/dashboard.test.ts
tests/wizard.files.test.ts
tests/wizard.submit.test.ts

Contributes to libero/reviewer#589

correct text representations article types

---

.github/push-image.sh

required for images pulled from hub that get passed into push-image.sh

fix: replace libero w. liberoadmin

---

src/application/wizard/resolvers.ts
src/application/wizard/service.ts
src/domain/submission/repositories/xpub-submission-root.test.ts
src/domain/submission/repositories/xpub-submission-root.ts
src/domain/submission/services/submission-service.ts
src/domain/submission/types.ts
src/schemas/submission.graphql
src/schemas/wizard.graphql
tests/wizard.pages.test.ts

closes https://github.com/libero/reviewer/issues/663 and closes https://github.com/libero/reviewer/issues/620

Save details page

---

src/application/wizard/resolvers.ts
src/schemas/wizard.graphql

Closes https://github.com/libero/reviewer/issues/668

Add progress feedback for supporting file

---

config/config.client.example.json
src/client-config.ts
tests/config/reviewer-submission-client.json

Removes unnecessary login config

removed login config

---

.github/workflows/ci.yml
.github/workflows/semver.yml

:man_facepalming: misplaced `/`

fix: broken .scripts path in workflows

---

src/schemas/submission.graphql

Contributes to libero/reviewer#696

Make author nullable

---

src/domain/file/services/file-service.ts
tests/test.utils.ts
tests/wizard.files.test.ts

Fix multi part more than5mb

---

src/application/wizard/resolvers.ts
src/domain/file/services/file-service.ts

This reverts commit c0acfe7e496f1b0fd080be0395cfc8249a849504.

Revert "debug (#159)"

---

src/application/wizard/resolvers.ts
src/application/wizard/service.test.ts
src/application/wizard/service.ts
src/domain/file/services/file-service.ts
src/schemas/wizard.graphql
tests/wizard.files.test.ts

672 delete supporting file

---

src/application/wizard/resolvers.ts
src/application/wizard/service.ts
src/domain/submission/repositories/xpub-submission-root.test.ts
src/domain/submission/repositories/xpub-submission-root.ts
src/domain/submission/services/models/submission-schema.ts
src/domain/submission/services/models/submission.ts
src/domain/submission/services/submission-service.ts
src/domain/submission/types.ts
src/domain/teams/repositories/types.ts
src/domain/teams/repositories/xpub-team.test.ts
src/domain/teams/repositories/xpub-team.ts
src/domain/teams/services/models/team.ts
src/domain/teams/services/team-service.ts
src/schemas/submission.graphql
src/schemas/wizard.graphql
tests/wizard.pages.test.ts

Closes https://github.com/libero/reviewer/issues/715

715 update team editors

---

src/application/wizard/resolvers.ts
src/schemas/submission.graphql
src/schemas/wizard.graphql
tests/wizard.files.test.ts

Closes https://github.com/libero/reviewer/issues/835

Match reviewer mocks and return ID

---

tests/dashboard.test.ts
tests/wizard.files.test.ts
tests/wizard.pages.test.ts
tests/wizard.submit.test.ts

closes  https://github.com/libero/reviewer/issues/891

Assert error checks where possible

---

src/domain/user/infrastructure/rest-user.test.ts
src/domain/user/infrastructure/rest-user.ts
src/domain/user/models/user-service.ts
src/domain/user/resolvers/user.ts

Add Authentication to the getEditors endpoint

---

src/domain/user/models/user-service.ts

Part of libero/reviewer#865 and libero/reviewer#938

Submission not to alter role (responsibility of User API)

---

src/domain/submission/services/models/submission-schema.ts
src/domain/submission/services/models/submission.test.ts

closes https://github.com/libero/reviewer/issues/962

align schema against new graphql schema

---

src/config.ts
src/domain/submission/services/storage/s3-store.test.ts
src/domain/submission/services/storage/s3-store.ts
src/domain/submission/services/storage/sftp-store.ts
src/domain/submission/services/storage/types.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/main.ts

add meca s3 upload

---

src/domain/submission/services/models/authorDetails-schema.test.ts
src/domain/submission/services/models/authorDetails-schema.ts
src/domain/submission/services/models/disclosure-schema.test.ts
src/domain/submission/services/models/disclosure-schema.ts
src/domain/submission/services/models/editorDetails-schema.test.ts
src/domain/submission/services/models/editorDetails-schema.ts
src/domain/submission/services/models/file-schema.test.ts
src/domain/submission/services/models/file-schema.ts
src/domain/submission/services/models/files-schema.test.ts
src/domain/submission/services/models/files-schema.ts
src/domain/submission/services/models/manuscriptDetails-schema.test.ts
src/domain/submission/services/models/manuscriptDetails-schema.ts
src/domain/submission/services/models/submission-schema.ts
src/domain/submission/services/models/submission.test.ts
src/domain/submission/services/models/submission.ts

Refactor Joi validation, add tests and account for special cases for feature articles

---

docker-compose.yml

adds meca config environment variables

add meca config

---

src/application/wizard/resolvers.ts
src/application/wizard/service.ts
src/domain/submission/services/submission-service.ts
src/schemas/submission.graphql
src/schemas/wizard.graphql

closes libero/reviewer#1022
integration tests will be done as part of libero/reviewer#973

add disclosure functionality

---

src/application/wizard/service.test.ts

Closes https://github.com/libero/reviewer/issues/1034
Separate tickets will be opened for each describe - reducing overall PR size into chunks

Skeleton of missing tests

---

src/application/wizard/service.test.ts
src/application/wizard/service.ts
src/domain/submission/repositories/xpub-submission-root.test.ts
src/domain/submission/repositories/xpub-submission-root.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/schemas/submission.graphql

Add lastStepVisited into schema & database

---

src/application/wizard/service.test.ts
src/application/wizard/service.ts

Closes https://github.com/libero/reviewer/issues/1047

Add getSubmission tests

---

src/application/wizard/service.test.ts
src/application/wizard/service.ts

Closes https://github.com/libero/reviewer/issues/1055

Save details page unit tests

---

src/application/wizard/service.test.ts
src/domain/submission/services/exporter/file-generators/article.test.data.ts
src/domain/submission/services/exporter/file-generators/article.ts
src/domain/submission/services/models/authorDetails-schema.test.ts
src/domain/submission/services/models/authorDetails-schema.ts
src/domain/submission/services/models/submission.test.ts
src/domain/submission/types.ts
src/domain/teams/repositories/xpub-team.test.ts
src/domain/teams/repositories/xpub-team.ts
src/domain/teams/services/team-service.test.ts

changed from aff to institution and convert at repository

---

src/application/wizard/service.test.ts
src/application/wizard/service.ts

closes https://github.com/libero/reviewer/issues/1052
closes https://github.com/libero/reviewer/issues/1053

delete supporting file and manuscript file

---

src/application/wizard/service.test.ts
src/application/wizard/service.ts

closes https://github.com/libero/reviewer/issues/1054

Save files page tests

---

src/application/wizard/service.test.ts

Closes https://github.com/libero/reviewer/issues/1049

Save editor page tests

---

src/application/wizard/service.test.ts

closes https://github.com/libero/reviewer/issues/1050

saveDisclosurePage - tests

---

src/application/wizard/service.test.ts
src/application/wizard/service.ts
tests/wizard.submit.test.ts

Closes https://github.com/libero/reviewer/issues/1051 and some cleaning up

1051 submit tests v2

---

src/domain/file/services/file-service.ts

Closes https://github.com/libero/reviewer/issues/1103

Move code from stale branch * 625-save-survey-results

---

src/domain/ejp-name/repositories/ejp-name.test.ts
src/domain/ejp-name/repositories/ejp-name.ts
src/domain/ejp-name/repositories/types.ts
src/domain/ejp-name/services/models/ejp-name.ts
src/domain/submission/services/exporter/file-generators/article.test.ts
src/domain/submission/services/exporter/file-generators/article.ts
src/domain/submission/services/exporter/meca-exporter.test.ts
src/domain/submission/services/exporter/meca-exporter.ts
src/domain/test-mocks/knex-mock.ts
src/main.ts

add ejp-name repository

---

src/application/wizard/service.ts
src/domain/submission/repositories/xpub-submission-root.test.ts
src/domain/submission/services/models/submission-schema.ts
src/domain/submission/services/models/submission.test.ts
src/domain/submission/services/models/submission.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/domain/submission/types.ts
src/schemas/submission.graphql
tests/dashboard.test.ts
tests/test.utils.ts
tests/wizard.submit.test.ts

Closes https://github.com/libero/reviewer/issues/1121

Submission state

---

package.json
src/domain/submission/services/exporter/file-generators/article.test.ts
src/domain/submission/services/exporter/file-generators/article.ts
src/domain/submission/services/exporter/jwt.ts
src/domain/submission/services/exporter/meca-exporter.test.ts
src/domain/submission/services/exporter/meca-exporter.ts
src/main.ts
yarn.lock

Closes https://github.com/libero/reviewer/issues/1165

Fix issue with no token being passed.

---

Makefile
src/application/dashboard/resolvers.ts
src/application/dashboard/service.test.ts
src/application/dashboard/service.ts
src/schemas/submission.graphql
tests/dashboard.test.ts
tests/wizard.submit.test.ts

Closes https://github.com/libero/reviewer/issues/1163

Fixes date format issues

---

docker-compose.yml
src/config.ts
src/domain/mail/services/mail-service.test.ts
src/domain/mail/services/mail-service.ts
src/domain/submission/services/emails/index.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/main.ts

Closes https://github.com/libero/reviewer/issues/1167

Email after submit

---

src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts

Meca export success

---

src/config.ts
src/domain/mail/services/mail-service.test.ts
src/domain/mail/services/mail-service.ts

Closes: https://github.com/libero/reviewer/issues/1226

Fix bug with AWS needing a promise call

---

src/application/wizard/resolvers.ts
src/domain/survey/repositories/knex-survey-response.test.ts
src/domain/survey/repositories/knex-survey-response.ts
src/domain/survey/services/models/survey-response.test.ts
src/domain/survey/services/models/survey-response.ts
src/domain/survey/services/survey-service.ts
src/domain/survey/types.ts

remove submissionId and replace all usages with string

---

src/domain/submission/repositories/xpub-submission-root.ts

Part of https://github.com/libero/reviewer/issues/1285

Add ordering

---

src/main.ts

Closes https://github.com/libero/reviewer/issues/1310

Properly handle sigterm

---

src/domain/submission/services/exporter/file-generators/article.ts
tests/config/reviewer-submission-client.json

Part of https://github.com/libero/reviewer/issues/1303

Rename human-biology-medicine to medicine

---

src/application/dashboard/resolvers.ts
src/application/dashboard/service.test.ts
src/application/dashboard/service.ts
src/domain/submission/services/exporter/file-generators/article.ts
src/domain/submission/services/models/submission.test.ts
src/domain/submission/services/models/submission.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/schemas/dashboard.graphql
src/schemas/submission.graphql

add saveArticleType resolver

---

package.json
yarn.lock

Remove unused packages as per https://github.com/libero/reviewer/issues/1230 to try ensure better stability to security for going live

Removed unused packages

---

src/application/wizard/service.ts
src/domain/submission/services/exporter/meca-import-callback.test.ts
src/domain/submission/services/exporter/meca-import-callback.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/main.ts

Align auditing

---

src/application/dashboard/service.test.ts
src/application/dashboard/service.ts
src/domain/file/services/file-service.test.ts
src/domain/file/services/file-service.ts
src/domain/submission/services/submission-service.test.ts
src/domain/submission/services/submission-service.ts
src/main.ts

Closes https://github.com/libero/reviewer/issues/1454

Delete submission functionality does not delete files

---

src/domain/file/services/file-service.test.ts
src/domain/file/services/file-service.ts

Closes https://github.com/libero/reviewer/issues/1468

Delete files from s3

---

src/application/dashboard/resolvers.ts
src/main.ts

Closes https://github.com/libero/reviewer/issues/1506

Fix bug with duplicate authors

---

src/domain/submission/services/models/authorDetails-schema.ts
src/domain/submission/services/models/editorDetails-schema.ts

DO NOT MERGE UNTIL MONDAY!
This aligns the back end validation with the front end validation to prevent 'on submit' errors that are difficult for the user to identify.

Email validation fix

---

yarn.lock

Hopefully resolving most of the dependabot alerts

Dependency upgrades

---

package.json
src/main.ts
tasks/merge-schemas.ts
yarn.lock

`graphql-import` has dependency vulnerabilities but is also deprecated. This replaces with the suggested `@graphql-tools`

Use @graphql-tools

---

src/domain/submission/services/submission-service.ts
src/main.ts

This is just copying implementation of https://github.com/libero/reviewer-submission/blob/654604b3bcf6e23858b7830fdc6a03f5c35b3cc8/src/application/wizard/service.ts#L126 from the submit.

Set correct status on failed retry

---

package.json
yarn.lock

Will monitor prod to make sure this doesn't break logging. I've reviewer config for old and new and it looks identical so no reason this shouldn't work

upgrade newrelic

---

package.json
yarn.lock

Have checked and `make start_dev` still works so happy this isn't a breaking change.

upgrade nodemon
